language: python
matrix:
  include:
    - python: 3.5
      dist: xenial
      sudo: true
before_install:
    - pip install --upgrade setuptools pip
    - pip install -r requirements.txt
install: python setup.py install
script:
  - coverage run setup.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)